### ISSUE TITLE
Configure the Back button to look the same on all pages

### ISSUE THREAD

**Issue by rajbos** [XpiritBV/copilot-videos#10]
The SKU's back button is different from the Detail page (video). I prefer the latter one.

- [ ] Make them look the same

**Comment by alvarotorrestx** [comment]
I'd like to help resolve this and contribute, please assign me :)

**Comment by virtually-stray** [comment]
Unfortunately, the other pull request seems to be slightly off as it uses the skull button style as the base for the changes, when it was supposed to be the other way around.

I've changed them all to look like the detail page button locally. I just need to make a pull request. If you please, you can assign the task to me and I'll open the pull request.

**Comment by virtually-stray** [comment]
https://github.com/XpiritBV/copilot-videos/pull/14#issue-2318293701

**Comment by rajbos** [comment]
A PR has been merged that fixes this. Closing this issue.
